export const instructions = [
  "As palavras devem ter pelo menos 4 letras",
  "Algumas palavras podem não estar listadas (termos científicos, substantivos próprios, jargões, palavras ofensivas, determinados pronomes, preposições e conjunções)",
  "Somente verbos no infinitivo são válidos. Exemplo: \"SUBIR\", \"CORRER\", \"JOGAR\"",
  "Ambos os gêneros da palavra são válidos. Exemplo: \"ALUNO\" e \"ALUNA\"",
  "Plurais não são válidos. Exemplo: \"LARANJAS\" e \"UVAS\", no plural, não são válidas",
  "Não há palavras acentuadas. Exemplo: CAFÉ e MAÇÃ"
];

export const contactEmail = "alex.fernandes.silva@ccc.ufcg.edu.br";

export const board = [
  [ "R", "T", "A", "G"],
  [ "A", "E", "P", "O"],
  [ "O", "D", "R", "T"],
  [ "E", "S", "C", "A"]
];

export const wordsList = [
  "ator",
  "caro",
  "crer",
  "sede",
  "seda",
  "reta",
  "rede",
  "rota",
  "rato",
  "doar",
  "doer",
  "dose",
  "data",
  "orca",
  "pata",
  "proa",
  "pera",
  "pago",
  "arte",
  "gata",
  "gota",
  "rata",
  "arder",
  "carpa",
  "tropa",
  "torso",
  "tarde",
  "droga",
  "porca",
  "porta",
  "pedra",
  "perto",
  "perda",
  "preta",
  "prato",
  "gordo",
  "gorda",
  "agora",
  "aperto",
  "torpedo",
  "perdoar",
  "apertado",
  "descrer",
  "optar",
  "repor",
  "adepto"
];

export const bonusWords = [
  "odre",
  "ater",
  "adro",
  "atar",
  "apor",
  "apta",
  "apto",
  "tear",
  "raer",
  "catre",
  "credo",
  "sedar",
  "treta",
  "tredo",
  "torpe",
  "depor",
  "oscar",
  "orear",
  "prear",
  "erado",
  "adeso",
  "atear",
  "atado",
  "apear",
  "terso",
  "cardar",
  "carepa",
  "carear",
  "careta",
  "tardar",
  "reptar",
  "reatar",
  "patear",
  "predar",
  "gatear",
  "tapear",
  "tapera",
  "escarpa",
  "tropear",
  "topetar",
  "areosca",
  "atopetar",
  "atordoar",
  "escarear",
  "escardear"
];
